## The NN Module

The torch.nn module in pytorch is a core library that provides variety of classes and function desiged to help build neural network effieciently and effectively.

## Key Components in torch.nn

1. Modules (Layers):

  **nn.Module:**  Base Class for all  neural network modules.

  **Common Layers:** nn.Linear() , nn.conv2D, nn.LSTM() , etc.

2. Activation Functions:

    **Functions:** nn.Relu, nn.Sigmoid and nn.Tanh

3. Loss Functions:

  **Loss Functions** :  nn.CrossEntropyLoss , nn.MSELoss, nn.NLLLoss

4. Container Modules:

  **container** :  nn.Sequential

5. Regularization and Dropout:

  **Regularization**:  nn.BatchNorm2D

  **Dropout** : nn.Dropout
   

In [1]:
import torch
import torch.nn as nn

In [2]:

# create model class
class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    # container
    self.network = nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid()
    )

  def forward(self, features):

    out = self.network(features)

    return out

In [3]:
# create dataset
features = torch.rand(10,5)

# create model
model = Model(features.shape[1])

# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.6187],
        [0.6346],
        [0.6256],
        [0.6364],
        [0.6333],
        [0.6378],
        [0.6065],
        [0.6385],
        [0.5946],
        [0.6136]], grad_fn=<SigmoidBackward0>)

In [8]:
l1_weights = model.network[0].weight
l1_bias =  model.network[0].bias

l2_weights = model.network[2].weight
l2_bias =  model.network[2].bias

In [9]:
print(l1_weights)
print("_________"*50)
print(l1_bias)

Parameter containing:
tensor([[-0.0601,  0.1492,  0.2910,  0.2711, -0.1239],
        [-0.2242, -0.4205,  0.4395, -0.1293,  0.4044],
        [ 0.0381,  0.4301,  0.1029, -0.3607, -0.2452]], requires_grad=True)
__________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________
Parameter containing:
tensor([-0.0240, -0.0665, -0.1102], requires_grad=True)


In [10]:
print(l2_weights)
print("_________"*50)
print(l2_bias)

Parameter containing:
tensor([[ 0.4216,  0.2755, -0.4349]], requires_grad=True)
__________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________
Parameter containing:
tensor([0.4075], requires_grad=True)


# The Optim Module

torch.optim is a module in Pytorch that provides a variety of optimization algorithms used to update the params of your model during training.

It includes common optimizers like SGD , Adam , RMSprop and More

## Model.parameters()

This method in Pytorch retrieves an iterator over all the trainable params in a model which includes weights and biases.